version: "3"

services:
  node:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/app"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"